import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { GlobalStoreContext } from "../context/Items";
const Layout = ({ children, title }) => {
  const { bucket, setbucket } = GlobalStoreContext();
  return (
    <>
      <Head>
        <title>{title ? title + "-" + "Ecommerce" : "Ecommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex text-black   min-h-screen flex-col justify-between">
        <header>
          <nav className="flex px-4 items-center justify-between h-12 shadow-md text-black no-underline">
            <Link href="/">
              <a className="text-lg text-black no-underline  font-bold">
                Ecommerce
              </a>
            </Link>
            <div className="text-black no-underline">
              <Link className="text-black no-underline" href="/Bucket">
                <a className="text-lg lg:p-4 md:p-2 sm:p-2 p-2 text-black no-underline  font-bold">
                  Cart{" "}
                  <span className="bg-red-500 m-1 p-1 text-white rounded-sm">
                    {bucket?.length}
                  </span>
                </a>
              </Link>
              <Link className="text-black no-underline" href="/login">
                <a className="text-lg text-black no-underline  font-bold">
                  Login
                </a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container w-full  mt-4">{children}</main>
        <footer className="bg-gray-200 text-center h-12 lg:text-left">
          <div
            className="text-gray-700 bg-cyan-500 text-center p-4"
            // style={{background-color: "rgba('0, 0, 0, 0.2')"}}
          >
            © 2021 Copyright:
            <a className="text-gray-800" href="https://tailwind-elements.com/">
              Tailwind Elements
            </a>
          </div>
        </footer>
      </div>
    </>
  );
};

export default Layout;
