import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home({ data }) {
  return (
    <div className="containers1">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="shadow-lg m-4 rounded-lg bg-orange-500 text-white font-serif p-4">
        <h1 className=" ">welcome to the next js</h1>
      </main>
    </div>
  );
}
// const="<div className=" container  fs-3 text-center my-5 mx-auto navs d-flex bg-black rounded-pill text-light">"
